# Naive_Bayes

## On Credit_Risk Data

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
cr = pd.read_csv("CreditRisk.csv")

In [4]:
cr.isnull().sum()

Loan_ID               0
Gender               24
Married               3
Dependents           25
Education             0
Self_Employed        55
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           27
Loan_Amount_Term     20
Credit_History       79
Property_Area         0
Loan_Status           0
dtype: int64

In [5]:
cr.Gender = cr.Gender.fillna("Male")
cr.Married = cr.Married.fillna("No")
cr.Dependents = cr.Dependents.fillna(0)
cr.Self_Employed = cr.Self_Employed.fillna("No")
cr.LoanAmount = cr.LoanAmount.fillna(cr.LoanAmount.mean())
cr.Loan_Amount_Term = cr.Loan_Amount_Term.fillna(cr.Loan_Amount_Term.mean())
cr.Credit_History = cr.Credit_History.fillna(0)

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [7]:
cr.Gender = le.fit_transform(cr.Gender)
cr.Married = le.fit_transform(cr.Married)
cr.Education = le.fit_transform(cr.Education)
cr.Self_Employed = le.fit_transform(cr.Self_Employed)
cr.Property_Area = le.fit_transform(cr.Property_Area)

In [8]:
cr.Loan_Status = cr.Loan_Status.replace({ "Y" :1 , "N" :0 })

In [9]:
cr.head()

Loan_ID  Gender  Married  Dependents  Education  Self_Employed  \
0  LP001002       1        0         0.0          0              0   
1  LP001003       1        1         1.0          0              0   
2  LP001005       1        1         0.0          0              1   
3  LP001006       1        1         0.0          1              0   
4  LP001008       1        0         0.0          0              0   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0   142.51153             360.0   
1             4583             1508.0   128.00000             360.0   
2             3000                0.0    66.00000             360.0   
3             2583             2358.0   120.00000             360.0   
4             6000                0.0   141.00000             360.0   

   Credit_History  Property_Area  Loan_Status  
0             1.0              2            1  
1             1.0              0            0  
2             1.0              2            1  
3             1.0              2            1  
4             1.0              2            1

In [10]:
cr_x = cr.iloc[ : , 1:12]
cr_y = cr.iloc[ : , 12]

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
cr_x_train, cr_x_test, cr_y_train, cr_y_test = train_test_split(cr_x,cr_y, test_size = 0.2, random_state = 555)

In [13]:
from sklearn.naive_bayes import MultinomialNB
NB = MultinomialNB()

In [14]:
NB.fit(cr_x_train, cr_y_train)
pred_nb = NB.predict(cr_x_test)

In [15]:
from sklearn.metrics import confusion_matrix

tab_nb = confusion_matrix(pred_nb, cr_y_test)
tab_nb

array([[23, 59],
       [38, 77]], dtype=int64)

In [16]:
cr_acc = tab_nb.diagonal().sum() / tab_nb.sum() * 100
cr_acc

50.76142131979695

## On CTG Data

In [17]:
ctg = pd.read_csv("CTG.csv")

In [18]:
ctg.NSP.value_counts()

1    1655
2     295
3     176
Name: NSP, dtype: int64

In [19]:
ctg_x = ctg.iloc[ : , [0,1,2] ]
ctg_y = ctg.iloc[ : , 3]

In [20]:
ctg_x_train, ctg_x_test, ctg_y_train, ctg_y_test = train_test_split(ctg_x,ctg_y, test_size = 0.2)

In [21]:
from sklearn.naive_bayes import MultinomialNB
NB = MultinomialNB()

In [22]:
NB.fit(ctg_x_train,ctg_y_train) # Model Building
perd_ctg = NB.predict(ctg_x_test)

In [23]:
from sklearn.metrics import confusion_matrix

tab_nb = confusion_matrix(perd_ctg, ctg_y_test)
tab_nb

array([[335,  62,  29],
       [  0,   0,   0],
       [  0,   0,   0]], dtype=int64)

In [24]:
cr_acc = tab_nb.diagonal().sum() / tab_nb.sum() * 100
cr_acc

78.63849765258216

## Class balancing by Manually

In [25]:
ctg = pd.read_csv("CTG.csv")

In [26]:
ctg_train, ctg_test = train_test_split(ctg, test_size = 0.2)

In [27]:
print(ctg.shape)
print(ctg_train.shape)
print(ctg_test.shape)

(2126, 4)
(1700, 4)
(426, 4)


In [28]:
ctg_train.NSP.value_counts()  # Class imbalance is there

1    1325
2     235
3     140
Name: NSP, dtype: int64

In [29]:
ctg_2 = ctg[ctg.NSP == 2]
ctg_2
ctg_3 = ctg[ctg.NSP == 3]
ctg_3

LB     AC     FM  NSP
5     134  0.001  0.000    3
6     134  0.001  0.000    3
7     122  0.000  0.000    3
8     122  0.000  0.000    3
9     122  0.000  0.000    3
20    129  0.000  0.340    3
22    128  0.000  0.334    3
23    128  0.000  0.000    3
24    128  0.000  0.000    3
25    124  0.000  0.000    3
26    124  0.000  0.000    3
27    124  0.000  0.000    3
54    148  0.000  0.003    3
93    148  0.000  0.000    3
94    148  0.000  0.005    3
116   123  0.000  0.000    3
240   125  0.000  0.009    3
296   148  0.000  0.015    3
297   148  0.000  0.012    3
298   148  0.000  0.019    3
309   141  0.000  0.003    3
317   150  0.000  0.025    3
319   150  0.000  0.024    3
320   150  0.000  0.028    3
323   135  0.000  0.000    3
324   135  0.000  0.000    3
328   146  0.000  0.000    3
334   144  0.000  0.011    3
335   146  0.000  0.003    3
339   133  0.000  0.000    3
340   133  0.000  0.000    3
341   133  0.000  0.000    3
342   133  0.000  0.000    3
351   140  0.000  0.019    3
352   140  0.000  0.022    3
363   135  0.000  0.013    3
364   135  0.000  0.016    3
403   151  0.000  0.000    3
418   137  0.000  0.000    3
466   144  0.000  0.001    3
467   144  0.000  0.002    3
468   144  0.000  0.002    3
469   151  0.000  0.002    3
470   151  0.000  0.002    3
471   150  0.000  0.004    3
472   150  0.000  0.000    3
473   150  0.000  0.003    3
474   150  0.000  0.001    3
475   150  0.000  0.002    3
596   148  0.000  0.002    3
597   148  0.000  0.003    3
644   123  0.000  0.000    3
645   123  0.000  0.000    3
650   123  0.000  0.000    3
651   123  0.000  0.000    3
652   123  0.000  0.002    3
653   123  0.000  0.000    3
654   123  0.000  0.000    3
682   132  0.000  0.306    3
683   132  0.000  0.298    3
690   133  0.000  0.360    3
697   131  0.001  0.369    3
698   131  0.000  0.335    3
700   130  0.000  0.346    3
701   131  0.000  0.323    3
702   131  0.000  0.375    3
703   130  0.000  0.346    3
704   130  0.000  0.353    3
706   133  0.000  0.000    3
720   129  0.000  0.007    3
749   134  0.000  0.003    3
750   134  0.000  0.000    3
751   134  0.000  0.003    3
767   135  0.000  0.000    3
768   135  0.000  0.000    3
769   134  0.000  0.000    3
770   134  0.000  0.000    3
771   130  0.000  0.001    3
773   130  0.000  0.000    3
823   152  0.000  0.000    3
824   152  0.000  0.000    3
944   136  0.001  0.000    3
1346  128  0.000  0.019    3
1347  128  0.000  0.019    3
1348  128  0.000  0.025    3
1349  128  0.000  0.028    3
1489  132  0.000  0.000    3
1491  132  0.000  0.000    3
1492  132  0.000  0.000    3
1681  110  0.003  0.002    3
1682  110  0.004  0.000    3
1683  110  0.003  0.002    3
1684  110  0.002  0.003    3
1685  110  0.004  0.002    3
1686  110  0.003  0.002    3
1708  131  0.000  0.003    3
1727  134  0.000  0.000    3
1749  134  0.002  0.002    3
1750  134  0.005  0.002    3
1751  134  0.004  0.001    3
1752  134  0.004  0.001    3
1753  134  0.004  0.001    3
1754  134  0.003  0.000    3
1755  134  0.003  0.000    3
1756  134  0.004  0.000    3
1761  120  0.000  0.000    3
1762  120  0.000  0.000    3
1763  120  0.000  0.000    3
1764  120  0.000  0.000    3
1765  120  0.000  0.000    3
1766  120  0.000  0.000    3
1767  120  0.000  0.000    3
1768  120  0.000  0.000    3
1769  120  0.000  0.000    3
1770  120  0.000  0.000    3
1771  120  0.000  0.000    3
1772  120  0.000  0.000    3
1773  120  0.000  0.000    3
1774  120  0.000  0.000    3
1775  120  0.000  0.000    3
1776  120  0.000  0.000    3
1790  121  0.000  0.002    3
1791  121  0.000  0.001    3
1792  121  0.000  0.001    3
1793  121  0.000  0.001    3
1794  121  0.000  0.001    3
1795  121  0.000  0.000    3
1878  138  0.000  0.002    3
1879  138  0.000  0.002    3
1880  138  0.000  0.000    3
1881  138  0.000  0.002    3
1903  130  0.002  0.000    3
1904  130  0.002  0.000    3
1905  130  0.001  0.000    3
1906  130  0.001  0.001    3
1907  130  0.002  0.002    3
1908  130  0.002  0.002    3
1909 

In [30]:
ctg_train_new = pd.concat([ctg_train, ctg_2, ctg_2, ctg_3, ctg_3, ctg_3, ctg_3, ctg_3, ctg_3, ctg_3])

In [31]:
ctg_train_new.shape

(3522, 4)

In [32]:
ctg_train_new.NSP.value_counts()

3    1372
1    1325
2     825
Name: NSP, dtype: int64

In [33]:
ctg_train_new_x = ctg_train_new.iloc[ : , [0,1,2]]
ctg_train_new_y = ctg_train_new.iloc[ : , 3]

ctg_test_x  = ctg_test.iloc[ : , [0,1,2]]
ctg_test_y = ctg_test.iloc[ : , 3]

In [34]:
from sklearn.naive_bayes import MultinomialNB
NB = MultinomialNB()

In [35]:
NB.fit(ctg_train_new_x,ctg_train_new_y) # Model Building
perd_ctg = NB.predict(ctg_test_x)

In [36]:
from sklearn.metrics import confusion_matrix

tab_nb = confusion_matrix(perd_ctg, ctg_test_y)
tab_nb

array([[  5,   0,   0],
       [  0,   0,   0],
       [325,  60,  36]], dtype=int64)

In [37]:
cr_acc = tab_nb.diagonal().sum() / tab_nb.sum() * 100
cr_acc

9.624413145539906